---
title: "Imputation Data Analysis"
author: "Anton Enright"
date: "2024-11-21"
output:
  github_document:
    toc: true
    fig_width: 8
    fig_height: 8
  pdf_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Load Libraries
```{r message=FALSE}
library(gtools)
library(ggplot2)
library(viridisLite)
library(viridis)
```


```{r fig.width=10,fig.height=7,dpi=300}
list.files()
data <- read.table("analysis/all_stats_by_chr.txt",header=FALSE,sep="\t")
colnames(data)=c("chr","pos","maf","info","concordance","r2")
data$chr <- paste0("chr",data$chr)
data <- data[mixedorder(data$chr),]

data$chr <- factor(data$chr,levels = mixedsort(unique(data$chr)),ordered = TRUE)

my_colours <- viridisLite::viridis(length(levels(data$chr)))


p <- ggplot(data, aes(x=chr, y=r2, fill=chr)) + scale_fill_manual(values = my_colours) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ggtitle("r2 values per chromsome") + xlab("Chromosome") + geom_hline(yintercept=median(data$r2), linetype="dashed", color = "red")
p
```


```{r fig.width=10,fig.height=7,dpi=300}
data_ind <- read.table("analysis/all_stats_by_individual.txt",header=FALSE,sep="\t")
colnames(data_ind)=c("chr","no","i","type","breed","sex","concordance","r2")
data_ind$breed=as.factor(data_ind$breed)
my_colours_breed <- viridisLite::viridis(length(levels(data_ind$breed)))

p <- ggplot(data_ind, aes(reorder(breed, r2, FUN=median), y = r2, fill=breed)) + scale_fill_manual(values = my_colours_breed) + geom_boxplot(outlier.size=0.3) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(legend.text = element_text(size = 2)) + ggtitle("r2 values by Breed") + xlab("Chromosome") + theme(legend.key.size = unit(0.3, 'cm')) + theme(legend.position="none") + theme(axis.text=element_text(size=4)) + coord_cartesian(ylim = c(0, 1.0))
p
```